### ISSUE TITLE
Please Fix to Gnome 3.38.1

### ISSUE THREAD

**Issue by andrewdomingues** [jeffchannell/jiggle#27] opened 2020-11-17 23:07 UTC
This is a Great extension, Please fix it.

**Comment by jeffchannell** [comment] 2020-11-18 03:00
Is this a duplicate of #25 ? Can you check logs for the same error? Thanks!

**Comment by jeffchannell** [comment] 2020-11-18 03:20
Closing as a duplicate of #25 - this seems like a straightforward patch, so expect a fix posted here soon.

**Closed by jeffchannell** 2020-11-18 03:20 UTC

**Comment by jeffchannell** [comment] 2020-11-22 04:38
New release is now available
